[build-system]
build-backend = "mesonpy"
requires = ["meson-python", "wheel", "numpy", "pybind11>=2.8.0"]

[project]
name = "set_cover"
version = "0.1.0"
authors = [
	{  name = "Matt Piekenbrock", email = "matt.piekenbrock@gmail.com" }
]
description = "Weighted Set Cover algorithms"
readme = "README.md"
packages = [
	{ include = "set_cover", from = "src" },
]
dependencies = [
  "numpy", 
	"combin"
]
license = {file = "LICENSE"}

