project:
  type: website
  output-dir: ../docs

website:
  bread-crumbs: true
  page-navigation: true
  navbar:
    background: primary
    search: false
    left: 
      - text: "Package overview"
        file: index.qmd
      - text: API Reference
        file: reference.qmd
    tools: 
      - icon: github
        href: https://github.com/peekxc/geomcover

interlinks:
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3/

filters: 
  - interlinks

metadata-files:
  - _sidebar.yml

format:
  html:
    css: styles.css

quartodoc:
  package: geomcover
  dir: .
  title: API Reference
  out_index: reference.qmd
  parser: google
  # sidebar: _sidebar.yml
  render_interlinks: False
  sections:
    - title: Set Cover (`cover`)
      desc: Functions to find minimum weight set covers.
      contents:
        - cover.coverage
        - cover.valid_cover
        - cover.set_cover
        - cover.set_cover_greedy
        - cover.set_cover_rr
        - cover.set_cover_ilp
        - cover.set_cover_sat
    - title: Linear Algebra (`linalg`)
      desc: Standard linear algebra algorithms. 
      contents: 
        - linalg.pca 
        - linalg.cmds
    - title: Geometry (`geometry`)
      desc: Algorithms for computing information on manifolds. 
      contents: 
        - geometry.tangent_bundle
        - geometry.bundle_weights
    - title: Cluster (`cluster`)
      desc: Algorithms related to clustering points in metric spaces. 
      contents: 
        - cluster.mean_shift
    - title: I/O (`io`)
      desc: Algorithms for loading, parsing, and cleaning set cover data sets.
      contents: 
        - io.load_set_cover
        - io.to_canonical
        - io.sets_to_sparse
        - io.sparse_to_sets
        - io.reindex_sparse