# wset_cover_sat { #geomcover.cover.wset_cover_sat }

`cover.wset_cover_sat(subsets, weights, return_solver=False, **kwargs)`

Computes an approximate solution to the weighted set cover problem via *weighted MaxSAT*.

This function converts the problem of finding a minimal weight set cover to a weighted MaxSAT instance, 
which is known to achieve at least an (8/7)-approximation of the optimal solution. The solver instance
used here is the Relaxed Cardinality Constraint solver (RC2) with Boolean lexicographic optimization (BLO)
and stratification (which requires python-sat to be installed).

## Parameters

| Name            | Type      | Description                                                                 | Default    |
|-----------------|-----------|-----------------------------------------------------------------------------|------------|
| `subsets`       | sparray   | (n x J) sparse matrix of J subsets whose union forms a cover over n points. | _required_ |
| `weights`       | ArrayLike | (J)-length array of subset weights.                                         | _required_ |
| `return_solver` | bool      | whether to return the SAT-solver instance. Defaults to False.               | `False`    |
| `**kwargs`      |           | additional keyword arguments to pass to the solver.                         | `{}`       |

## Returns

| Type   | Description                                                                                    |
|--------|------------------------------------------------------------------------------------------------|
| tuple  | (s, c) where s is a boolean array indicating which subsets are in the cover and c is its cost. |